### ISSUE TITLE
(optionally) Export only a collection within vaultwarden organisation 

### ISSUE THREAD

**Issue by richardwonka** [alex3305/hassio-addons#53]
I have an organisation in vaultwarden specifically for potentially shareable admin secrets which contains, among others, my HA secrets. 

For the current implementation of this add-on I would have to create a new org, then move some of these secrets from their dedicated place to the new org. 

Part of me would prefer keeping the number of orgs minimal. 

It would be nice to have the option of this add-on only exporting a specified collection _within_ the organisation. So i could add a collection _Home Assistant_ in my org _General Admin Accounts_ and collect in that one the secrets I want to appear in HA. 

The only problem I see is that this way the add-on could potentially have access to other secrets in the org, but it would be use as designed for vaultwarden. 

Any thoughts?

**Comment by richardwonka** [comment]
I just checked: Limiting access to a particular collection in an org is possible.

**Comment by alex3305** [comment]
Closed because I will archive this repo.
