### ISSUE TITLE
Installation traefik addon

### ISSUE THREAD

**Issue by norj5** [alex3305/hassio-addons#8]
Hello, 
The traefik addon doesn´t install. Could you help me with this?

Thankyou

**Comment by alex3305** [comment]
Which platform are you running on? And can you provide the logging from Home Assistant supervisor when installing?

**Comment by norj5** [comment]
I have installed in a raspberrypi 4. How can i see the logs? In the addon page of traefik there is no log because it doesn´t install. In my other addon, the log page appears when i have installed the addon. I push the install button but nothing hapens.

**Comment by norj5** [comment]
when i try to paste the system log in here, and send it, the antivirus blocks a threat. 
"An attempt to inject a command towards your system through a dangerous URL was made by 140.82.118.3. We blocked the connection to prevent malicious commands from being executed on the device and across the network"

**Comment by alex3305** [comment]
Unfortunately I don't own a Raspberry Pi 4 and thus am not quite sure what goes wrong. And I'm also not capable of testing this. I would really like to see some error logging from Home Assistant Supervisor as seen here:
![image](https://user-images.githubusercontent.com/5155694/86485689-a9feab80-bd59-11ea-936d-38e07ae54d61.png)

If you know how to run Docker images by itself you could also try to build the stripped down `Dockerfile ` below and see what goes wrong. Maybe I can help you with that.

```dockerfile
FROM hassioaddons/base

ARG TRAEFIK_VERSION=2.2.1
ARG BUILD_ARCH=armv7

RUN apk add --no-cache python3 py3-pip nginx
RUN pip3 install "j2cli[yaml]"
RUN wget --quiet -O /tmp/traefik.tar.gz "https://github.com/containous/traefik/releases/download/v${TRAEFIK_VERSION}/traefik_v${TRAEFIK_VERSION}_linux_${BUILD_ARCH}.tar.gz"
RUN tar xzvf /tmp/traefik.tar.gz -C /usr/local/bin traefik
RUN chmod a+x /usr/local/bin/traefik
RUN rm -f /tmp/traefik.tar.gz
```

You could build this with the following command from within the directory that the `Dockerfile` is located:

```bash
docker build -t traefik-test .
```

**Comment by norj5** [comment]
GitHub doesn’t let me paste the system log. I will send you a image later on.  I will try what you have sent.  My idea is to use this add on to proxy one rasp pi 4 with HA and another with nextcloud

Than you very much for replaying. Is the first time I use github

**Comment by leakypixel** [comment]
Hi @alex3305 and thanks for your work on this addon!

Apologies for commenting on a stale issue, but I'm seeing the same problem. The logs from the supervisor show the following:
```
20-09-15 12:46:53 INFO (SyncWorker_4) [supervisor.docker.addon] Start build 32de6d38/aarch64-addon-traefik:3.0.3
20-09-15 12:47:22 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build 32de6d38/aarch64-addon-traefik:3.0.3: The command '/bin/ash -o pipefail -c apk add --no-cache python3 py3-pip nginx &&     pip3 install "j2cli[yaml]" &&     wget --quiet -O /tmp/traefik.tar.gz "https://github.com/containous/traefik/releases/download/v${TRAEFIK_VERSION}/traefik_v${TRAEFIK_VERSION}_linux_${BUILD_ARCH}.tar.gz" &&     tar xzvf /tmp/traefik.tar.gz -C /usr/local/bin traefik &&     chmod a+x /usr/local/bin/traefik &&     chmod a+x /run.sh &&     rm -f /tmp/traefik.tar.gz' returned a non-zero code: 1
20-09-15 12:48:01 INFO (SyncWorker_1) [supervisor.docker.addon] Start build 32de6d38/aarch64-addon-traefik:3.0.3
20-09-15 12:48:24 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build 32de6d38/aarch64-addon-traefik:3.0.3: The command '/bin/ash -o pipefail -c apk add --no-cache python3 py3-pip nginx &&     pip3 install "j2cli[yaml]" &&     wget --quiet -O /tmp/traefik.tar.gz "https://github.com/containous/traefik/releases/download/v${TRAEFIK_VERSION}/traefik_v${TRAEFIK_VERSION}_linux_${BUILD_ARCH}.tar.gz" &&     tar xzvf /tmp/traefik.tar.gz -C /usr/local/bin traefik &&     chmod a+x /usr/local/bin/traefik &&     chmod a+x /run.sh &&     rm -f /tmp/traefik.tar.gz' returned a non-zero code: 1
```

I'm having a look if I can get some more detailed information out of that but so far no luck!

**Comment by leakypixel** [comment]
Seems to have been 64-bit builds only and was related to the BUILD_ARCH environment variable - I've made a PR with the issue fixed :) It's tested on a RPi4-64 running HassOS 5.2 and HassOS 4.13 and seems to be fine.
